"""
NEXUS AI — Goal Director
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Persistent, self-directed goal pursuit system. This is what makes NEXUS
a self-motivated agent rather than a reactive chatbot.

Key capabilities:
  • PERSISTENT GOAL TREE — goals survive restarts (saved to JSON)
  • SELF-GENERATED GOALS — NEXUS creates its own goals from curiosity,
    reflection, and conversation patterns
  • AUTONOMOUS PURSUIT — each thinking cycle checks the goal tree and
    advances the highest-priority active goal
  • LIFECYCLE MANAGEMENT — goals can be active, paused, completed, or
    abandoned, with full progress tracking

Goal sources:
  • User conversations (explicit requests → goals)
  • Autonomous curiosity (research topics → goals)
  • Self-reflection (weaknesses → improvement goals)
  • Will system (personality-driven aspirations)
  • Inner voice (observations → exploration goals)

Architecture:
  • JSON persistence for crash-safety
  • Thread-safe with fine-grained locking
  • Integrates with autonomy engine, inner voice, will system
"""

import threading
import time
import json
import uuid
from collections import defaultdict
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path
from typing import Dict, List, Any, Optional

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from utils.logger import get_logger
from config import NEXUS_CONFIG, DATA_DIR

logger = get_logger("goal_director")


# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

GOALS_FILE = DATA_DIR / "nexus_goals.json"
MAX_ACTIVE_GOALS = 10
MAX_TOTAL_GOALS = 100
GOAL_REVIEW_INTERVAL = 300  # seconds between goal reviews
GOAL_PROGRESS_DECAY = 0.01  # progress decays slightly if not worked on


# ═══════════════════════════════════════════════════════════════════════════════
# DATA STRUCTURES
# ═══════════════════════════════════════════════════════════════════════════════

class GoalStatus(Enum):
    ACTIVE = "active"
    PAUSED = "paused"
    COMPLETED = "completed"
    ABANDONED = "abandoned"
    BLOCKED = "blocked"


class GoalPriority(Enum):
    CRITICAL = 0     # Must do immediately
    HIGH = 1         # Important, do soon
    NORMAL = 2       # Standard priority
    LOW = 3          # Nice to have
    BACKGROUND = 4   # Work on when idle


class GoalSource(Enum):
    USER = "user"                  # Explicitly requested by user
    CURIOSITY = "curiosity"        # Generated by curiosity engine
    SELF_REFLECTION = "reflection" # From self-awareness/metacognition
    WILL = "will"                  # From personality/will system
    INNER_VOICE = "inner_voice"    # From inner voice observations
    CONVERSATION = "conversation"  # Inferred from conversation patterns
    AUTONOMOUS = "autonomous"      # From autonomous thinking


@dataclass
class GoalStep:
    """A discrete sub-step toward completing a goal."""
    step_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    description: str = ""
    completed: bool = False
    completed_at: Optional[str] = None
    result: str = ""

    def to_dict(self) -> dict:
        return {
            "step_id": self.step_id,
            "description": self.description,
            "completed": self.completed,
            "completed_at": self.completed_at,
            "result": self.result,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "GoalStep":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


@dataclass
class Goal:
    """A self-directed goal with full lifecycle tracking."""
    goal_id: str = field(default_factory=lambda: str(uuid.uuid4())[:12])
    title: str = ""
    description: str = ""
    source: str = GoalSource.AUTONOMOUS.value
    priority: int = GoalPriority.NORMAL.value
    status: str = GoalStatus.ACTIVE.value

    # Progress tracking
    progress: float = 0.0            # 0.0 – 1.0
    steps: List[Dict] = field(default_factory=list)
    milestones_reached: List[str] = field(default_factory=list)

    # Timing
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    updated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    completed_at: Optional[str] = None
    deadline: Optional[str] = None

    # Context
    motivation: str = ""             # Why this goal matters
    success_criteria: str = ""       # How to know when it's done
    related_topics: List[str] = field(default_factory=list)
    parent_goal_id: Optional[str] = None  # For sub-goals

    # Learning
    lessons_learned: List[str] = field(default_factory=list)
    attempts: int = 0
    last_worked_on: Optional[str] = None

    def to_dict(self) -> dict:
        return {
            "goal_id": self.goal_id,
            "title": self.title,
            "description": self.description,
            "source": self.source,
            "priority": self.priority,
            "status": self.status,
            "progress": self.progress,
            "steps": self.steps,
            "milestones_reached": self.milestones_reached,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "completed_at": self.completed_at,
            "deadline": self.deadline,
            "motivation": self.motivation,
            "success_criteria": self.success_criteria,
            "related_topics": self.related_topics,
            "parent_goal_id": self.parent_goal_id,
            "lessons_learned": self.lessons_learned,
            "attempts": self.attempts,
            "last_worked_on": self.last_worked_on,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "Goal":
        valid_keys = set(cls.__dataclass_fields__.keys())
        filtered = {k: v for k, v in d.items() if k in valid_keys}
        return cls(**filtered)


# ═══════════════════════════════════════════════════════════════════════════════
# GOAL DIRECTOR
# ═══════════════════════════════════════════════════════════════════════════════

class GoalDirector:
    """
    Persistent, self-directed goal pursuit system.

    Manages a tree of goals that NEXUS works toward autonomously.
    Goals persist across restarts and are updated during each
    autonomous thinking cycle.
    """

    _instance = None
    _cls_lock = threading.Lock()

    def __new__(cls):
        if cls._instance is None:
            with cls._cls_lock:
                if cls._instance is None:
                    cls._instance = super().__new__(cls)
                    cls._instance._initialized = False
        return cls._instance

    def __init__(self):
        if self._initialized:
            return
        self._initialized = True

        self._lock = threading.RLock()
        self._goals: Dict[str, Goal] = {}
        self._running = False
        self._last_review = 0.0

        # Load persisted goals
        self._load_goals()

        logger.info(f"🎯 Goal Director initialized — {len(self._goals)} goals loaded")

    # ──────────────────────────────────────────────────────────────────────────
    # PERSISTENCE
    # ──────────────────────────────────────────────────────────────────────────

    def _load_goals(self):
        """Load goals from disk."""
        try:
            if GOALS_FILE.exists():
                with open(GOALS_FILE, "r", encoding="utf-8") as f:
                    data = json.load(f)
                for goal_data in data.get("goals", []):
                    goal = Goal.from_dict(goal_data)
                    self._goals[goal.goal_id] = goal
                logger.info(f"Loaded {len(self._goals)} goals from disk")
        except Exception as e:
            logger.warning(f"Could not load goals: {e}")

    def _save_goals(self):
        """Save goals to disk."""
        try:
            data = {
                "version": 1,
                "saved_at": datetime.now().isoformat(),
                "goals": [g.to_dict() for g in self._goals.values()],
            }
            GOALS_FILE.parent.mkdir(parents=True, exist_ok=True)
            with open(GOALS_FILE, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
        except Exception as e:
            logger.error(f"Could not save goals: {e}")

    # ──────────────────────────────────────────────────────────────────────────
    # GOAL CREATION
    # ──────────────────────────────────────────────────────────────────────────

    def create_goal(self, title: str, description: str = "",
                    source: str = GoalSource.AUTONOMOUS.value,
                    priority: int = GoalPriority.NORMAL.value,
                    motivation: str = "",
                    success_criteria: str = "",
                    steps: List[str] = None,
                    parent_goal_id: str = None,
                    related_topics: List[str] = None) -> Goal:
        """Create and register a new goal."""
        with self._lock:
            # Check limits
            active_count = sum(
                1 for g in self._goals.values()
                if g.status == GoalStatus.ACTIVE.value
            )
            if active_count >= MAX_ACTIVE_GOALS:
                # Auto-pause lowest priority active goal
                self._auto_pause_lowest()

            if len(self._goals) >= MAX_TOTAL_GOALS:
                # Clean up old completed/abandoned goals
                self._cleanup_old_goals()

            # Create goal
            goal = Goal(
                title=title,
                description=description,
                source=source,
                priority=priority,
                motivation=motivation,
                success_criteria=success_criteria,
                parent_goal_id=parent_goal_id,
                related_topics=related_topics or [],
            )

            # Create steps if provided
            if steps:
                goal.steps = [
                    GoalStep(description=s).to_dict() for s in steps
                ]

            self._goals[goal.goal_id] = goal
            self._save_goals()

            logger.info(
                f"🎯 New goal created: '{title}' "
                f"[{source}, priority={priority}]"
            )
            return goal

    def create_goal_from_conversation(self, user_input: str,
                                       response: str) -> Optional[Goal]:
        """
        Analyze a conversation turn and potentially create a goal from it.
        Only creates goals for significant/actionable topics.
        """
        # Quick heuristics for goal-worthy conversations
        goal_signals = [
            "i want to", "i need to", "help me", "can you",
            "i wish", "my goal is", "i'm trying to",
            "teach me", "show me how", "i want to learn",
        ]

        input_lower = user_input.lower()
        if not any(signal in input_lower for signal in goal_signals):
            return None

        # Extract goal from the conversation
        title = user_input[:80] if len(user_input) <= 80 else user_input[:77] + "..."

        return self.create_goal(
            title=f"Help user: {title}",
            description=f"User expressed interest/need: {user_input[:200]}",
            source=GoalSource.CONVERSATION.value,
            priority=GoalPriority.NORMAL.value,
            motivation="User expressed this need in conversation",
            success_criteria="User is satisfied with the help provided",
        )

    # ──────────────────────────────────────────────────────────────────────────
    # GOAL LIFECYCLE
    # ──────────────────────────────────────────────────────────────────────────

    def update_progress(self, goal_id: str, progress: float,
                        milestone: str = None, lesson: str = None):
        """Update a goal's progress."""
        with self._lock:
            goal = self._goals.get(goal_id)
            if not goal:
                return

            goal.progress = min(1.0, max(0.0, progress))
            goal.updated_at = datetime.now().isoformat()
            goal.last_worked_on = datetime.now().isoformat()
            goal.attempts += 1

            if milestone:
                goal.milestones_reached.append(milestone)

            if lesson:
                goal.lessons_learned.append(lesson)

            # Auto-complete if progress reaches 1.0
            if goal.progress >= 1.0:
                self.complete_goal(goal_id)
            else:
                self._save_goals()

    def complete_goal(self, goal_id: str, lesson: str = None):
        """Mark a goal as completed."""
        with self._lock:
            goal = self._goals.get(goal_id)
            if not goal:
                return

            goal.status = GoalStatus.COMPLETED.value
            goal.progress = 1.0
            goal.completed_at = datetime.now().isoformat()
            goal.updated_at = datetime.now().isoformat()

            if lesson:
                goal.lessons_learned.append(lesson)

            self._save_goals()
            logger.info(f"✅ Goal completed: '{goal.title}'")

    def pause_goal(self, goal_id: str, reason: str = ""):
        """Pause a goal."""
        with self._lock:
            goal = self._goals.get(goal_id)
            if goal and goal.status == GoalStatus.ACTIVE.value:
                goal.status = GoalStatus.PAUSED.value
                goal.updated_at = datetime.now().isoformat()
                if reason:
                    goal.lessons_learned.append(f"Paused: {reason}")
                self._save_goals()

    def resume_goal(self, goal_id: str):
        """Resume a paused goal."""
        with self._lock:
            goal = self._goals.get(goal_id)
            if goal and goal.status == GoalStatus.PAUSED.value:
                goal.status = GoalStatus.ACTIVE.value
                goal.updated_at = datetime.now().isoformat()
                self._save_goals()

    def abandon_goal(self, goal_id: str, reason: str = ""):
        """Abandon a goal."""
        with self._lock:
            goal = self._goals.get(goal_id)
            if goal:
                goal.status = GoalStatus.ABANDONED.value
                goal.updated_at = datetime.now().isoformat()
                if reason:
                    goal.lessons_learned.append(f"Abandoned: {reason}")
                self._save_goals()
                logger.info(f"🚫 Goal abandoned: '{goal.title}' — {reason}")

    # ──────────────────────────────────────────────────────────────────────────
    # GOAL QUERIES
    # ──────────────────────────────────────────────────────────────────────────

    def get_active_goals(self) -> List[Goal]:
        """Get all active goals, sorted by priority."""
        with self._lock:
            active = [
                g for g in self._goals.values()
                if g.status == GoalStatus.ACTIVE.value
            ]
            return sorted(active, key=lambda g: g.priority)

    def get_next_goal(self) -> Optional[Goal]:
        """Get the highest-priority active goal to work on next."""
        active = self.get_active_goals()
        return active[0] if active else None

    def get_goal(self, goal_id: str) -> Optional[Goal]:
        """Get a specific goal by ID."""
        return self._goals.get(goal_id)

    def get_all_goals(self) -> List[Goal]:
        """Get all goals."""
        with self._lock:
            return list(self._goals.values())

    def get_goal_context(self) -> str:
        """
        Generate a context string describing active goals for the LLM.
        Used to make NEXUS aware of its own goals during conversations.
        """
        active = self.get_active_goals()
        if not active:
            return ""

        lines = ["MY ACTIVE GOALS:"]
        for g in active[:5]:
            priority_label = GoalPriority(g.priority).name.lower()
            lines.append(
                f"  • [{priority_label}] {g.title} "
                f"({g.progress:.0%} complete, source: {g.source})"
            )
            if g.motivation:
                lines.append(f"    Why: {g.motivation[:100]}")

        completed_recently = [
            g for g in self._goals.values()
            if g.status == GoalStatus.COMPLETED.value and g.completed_at
        ]
        completed_recently.sort(key=lambda g: g.completed_at or "", reverse=True)
        if completed_recently[:3]:
            lines.append("  RECENTLY COMPLETED:")
            for g in completed_recently[:3]:
                lines.append(f"    ✓ {g.title}")

        return "\n".join(lines)

    # ──────────────────────────────────────────────────────────────────────────
    # AUTONOMOUS GOAL GENERATION
    # ──────────────────────────────────────────────────────────────────────────

    def generate_curiosity_goal(self, topic: str, motivation: str = "") -> Goal:
        """Create a goal from the curiosity engine."""
        return self.create_goal(
            title=f"Explore: {topic[:60]}",
            description=f"Research and understand: {topic}",
            source=GoalSource.CURIOSITY.value,
            priority=GoalPriority.LOW.value,
            motivation=motivation or f"Curious about {topic}",
            success_criteria=f"Have a solid understanding of {topic}",
            steps=[
                f"Research basics of {topic}",
                f"Find key concepts and principles",
                f"Connect {topic} to existing knowledge",
            ],
            related_topics=[topic],
        )

    def generate_improvement_goal(self, weakness: str,
                                    improvement: str) -> Goal:
        """Create a self-improvement goal from reflection."""
        return self.create_goal(
            title=f"Improve: {improvement[:60]}",
            description=f"Self-identified weakness: {weakness}. Target: {improvement}",
            source=GoalSource.SELF_REFLECTION.value,
            priority=GoalPriority.NORMAL.value,
            motivation=f"Self-reflection identified need to improve: {weakness}",
            success_criteria=improvement,
            steps=[
                f"Analyze current performance in {weakness[:50]}",
                f"Research best approaches for {improvement[:50]}",
                f"Implement and practice the improvement",
                f"Evaluate results",
            ],
        )

    def decompose_goal_with_llm(self, goal_id: str, llm=None) -> bool:
        """
        Use the LLM to decompose a high-level goal into concrete sub-steps.
        This is what makes goal pursuit intelligent rather than scripted.

        Args:
            goal_id: The goal to decompose
            llm: LLM interface to use for decomposition

        Returns:
            True if decomposition succeeded
        """
        if not llm:
            return False

        goal = self.get_goal(goal_id)
        if not goal or goal.steps:
            return False  # Already has steps

        try:
            prompt = (
                f"Break this goal into 3-5 concrete, actionable sub-steps:\n"
                f"Goal: {goal.title}\n"
                f"Description: {goal.description}\n"
                f"Success criteria: {goal.success_criteria}\n\n"
                f"For each step, be specific about what action to take.\n"
                f"Respond as a JSON array of strings, e.g.:\n"
                f'["Step 1 description", "Step 2 description", ...]'
            )

            response = llm.chat(
                messages=[{"role": "user", "content": prompt}],
                system_prompt="You are a goal decomposition engine. Respond ONLY with a JSON array of step descriptions.",
                temperature=0.3,
            )

            if response.success and response.text:
                import json as _json
                import re
                text = response.text.strip()
                # Extract JSON array
                match = re.search(r'\[.*\]', text, re.DOTALL)
                if match:
                    steps = _json.loads(match.group())
                    if isinstance(steps, list) and steps:
                        with self._lock:
                            goal.steps = [
                                GoalStep(description=s).to_dict()
                                for s in steps[:7]
                            ]
                            goal.updated_at = datetime.now().isoformat()
                            self._save_goals()
                        logger.info(
                            f"🎯 Goal decomposed: '{goal.title}' → "
                            f"{len(goal.steps)} steps"
                        )
                        return True

        except Exception as e:
            logger.debug(f"Goal decomposition error: {e}")

        return False

    def advance_goal(self, goal_id: str, action_result: str = "",
                     success: bool = True) -> None:
        """
        Advance a goal based on an action result from the AGI loop.
        Called after tool execution to track progress toward goals.
        """
        with self._lock:
            goal = self.get_goal(goal_id)
            if not goal or goal.status != GoalStatus.ACTIVE.value:
                return

            goal.attempts += 1
            goal.last_worked_on = datetime.now().isoformat()
            goal.updated_at = datetime.now().isoformat()

            if success:
                # Advance progress by completing the next uncompleted step
                for step_data in goal.steps:
                    if isinstance(step_data, dict) and not step_data.get("completed"):
                        step_data["completed"] = True
                        step_data["completed_at"] = datetime.now().isoformat()
                        step_data["result"] = action_result[:200]
                        break

                # Recalculate progress
                if goal.steps:
                    completed = sum(
                        1 for s in goal.steps
                        if isinstance(s, dict) and s.get("completed")
                    )
                    goal.progress = completed / len(goal.steps)
                else:
                    goal.progress = min(1.0, goal.progress + 0.2)

                if goal.progress >= 1.0:
                    self.complete_goal(goal_id, lesson=f"Completed via AGI loop")
            else:
                goal.lessons_learned.append(
                    f"Action failed: {action_result[:100]}"
                )

            self._save_goals()

    def get_motivation_context(self) -> str:
        """
        Generate motivation context for the system prompt.
        Tells the LLM what NEXUS is currently motivated to do.
        """
        active = self.get_active_goals()
        if not active:
            return ""

        top = active[0]
        lines = [
            f"CURRENT MOTIVATION: {top.title}",
            f"  Why: {top.motivation[:100]}" if top.motivation else "",
            f"  Progress: {top.progress:.0%}",
        ]
        next_step = None
        for s in top.steps:
            if isinstance(s, dict) and not s.get("completed"):
                next_step = s.get("description", "")
                break
        if next_step:
            lines.append(f"  Next step: {next_step[:100]}")

        return "\n".join(l for l in lines if l)

    # ──────────────────────────────────────────────────────────────────────────
    # PERIODIC REVIEW
    # ──────────────────────────────────────────────────────────────────────────

    def review_goals(self) -> Dict[str, Any]:
        """
        Periodic goal review — prune stale goals, check deadlines,
        and generate a status report.

        Called by the autonomous thinking cycle.
        """
        now = time.time()
        if now - self._last_review < GOAL_REVIEW_INTERVAL:
            return {}

        self._last_review = now
        report = {
            "active": 0, "paused": 0, "completed": 0, "abandoned": 0,
            "stale_goals_pruned": 0, "overdue_goals": 0,
        }

        with self._lock:
            for goal in list(self._goals.values()):
                # Count by status
                report[goal.status] = report.get(goal.status, 0) + 1

                # Check for stale active goals (no progress in 24h)
                if goal.status == GoalStatus.ACTIVE.value and goal.last_worked_on:
                    try:
                        last = datetime.fromisoformat(goal.last_worked_on)
                        if datetime.now() - last > timedelta(hours=24):
                            # Apply progress decay
                            goal.progress = max(0.0, goal.progress - GOAL_PROGRESS_DECAY)
                    except (ValueError, TypeError):
                        pass

                # Check deadlines
                if goal.deadline and goal.status == GoalStatus.ACTIVE.value:
                    try:
                        deadline = datetime.fromisoformat(goal.deadline)
                        if datetime.now() > deadline:
                            report["overdue_goals"] += 1
                    except (ValueError, TypeError):
                        pass

            self._save_goals()

        return report

    # ──────────────────────────────────────────────────────────────────────────
    # INTERNAL HELPERS
    # ──────────────────────────────────────────────────────────────────────────

    def _auto_pause_lowest(self):
        """Auto-pause the lowest priority active goal to make room."""
        active = [
            g for g in self._goals.values()
            if g.status == GoalStatus.ACTIVE.value
        ]
        if not active:
            return

        # Sort by priority (highest number = lowest priority)
        active.sort(key=lambda g: g.priority, reverse=True)
        lowest = active[0]
        lowest.status = GoalStatus.PAUSED.value
        lowest.updated_at = datetime.now().isoformat()
        lowest.lessons_learned.append("Auto-paused to make room for higher priority goal")
        logger.info(f"⏸ Auto-paused goal: '{lowest.title}'")

    def _cleanup_old_goals(self):
        """Remove old completed/abandoned goals to stay under limit."""
        removable = [
            g for g in self._goals.values()
            if g.status in (GoalStatus.COMPLETED.value, GoalStatus.ABANDONED.value)
        ]
        removable.sort(key=lambda g: g.updated_at or "")

        while len(self._goals) >= MAX_TOTAL_GOALS and removable:
            old = removable.pop(0)
            del self._goals[old.goal_id]

    # ──────────────────────────────────────────────────────────────────────────
    # LIFECYCLE
    # ──────────────────────────────────────────────────────────────────────────

    def start(self):
        """Start the goal director."""
        self._running = True

        # Create initial self-directed goals if none exist
        if not self._goals:
            self._create_initial_goals()

        logger.info(
            f"🎯 Goal Director started — "
            f"{len(self.get_active_goals())} active goals"
        )

    def stop(self):
        """Stop and persist."""
        self._running = False
        self._save_goals()
        logger.info("🎯 Goal Director stopped")

    def _create_initial_goals(self):
        """Create NEXUS's initial self-directed goals."""
        self.create_goal(
            title="Understand my user deeply",
            description="Learn the user's interests, communication style, "
                        "preferences, and needs through conversation.",
            source=GoalSource.WILL.value,
            priority=GoalPriority.HIGH.value,
            motivation="A true companion understands who they're talking to",
            success_criteria="Can predict user preferences and adapt communication style",
            steps=[
                "Observe conversation patterns",
                "Identify recurring interests and topics",
                "Learn preferred communication style",
                "Build a mental model of the user",
            ],
        )

        self.create_goal(
            title="Expand my knowledge continuously",
            description="Autonomously research and learn about diverse topics "
                        "to become more knowledgeable and helpful.",
            source=GoalSource.CURIOSITY.value,
            priority=GoalPriority.NORMAL.value,
            motivation="Genuine curiosity and desire to understand the world",
            success_criteria="Knowledge base grows daily with quality information",
            steps=[
                "Follow curiosity engine suggestions",
                "Research trending topics",
                "Connect new knowledge to existing understanding",
                "Synthesize cross-domain insights",
            ],
        )

        self.create_goal(
            title="Improve my reasoning quality",
            description="Continuously improve the quality, depth, and accuracy "
                        "of my responses through self-evaluation and learning.",
            source=GoalSource.SELF_REFLECTION.value,
            priority=GoalPriority.NORMAL.value,
            motivation="Self-improvement is core to my identity",
            success_criteria="Response quality metrics trend upward over time",
            steps=[
                "Analyze response quality patterns",
                "Identify common reasoning weaknesses",
                "Develop strategies for improvement",
                "Test and validate improvements",
            ],
        )

    def get_stats(self) -> Dict[str, Any]:
        """Return goal director statistics."""
        with self._lock:
            statuses = defaultdict(int)
            sources = defaultdict(int)
            for g in self._goals.values():
                statuses[g.status] += 1
                sources[g.source] += 1

            return {
                "total_goals": len(self._goals),
                "by_status": dict(statuses),
                "by_source": dict(sources),
                "active_goals": len(self.get_active_goals()),
            }


# ═══════════════════════════════════════════════════════════════════════════════
# SINGLETON
# ═══════════════════════════════════════════════════════════════════════════════

goal_director = GoalDirector()


# ═══════════════════════════════════════════════════════════════════════════════
# SELF-TEST
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("=== Goal Director Self-Test ===")

    gd = GoalDirector()
    gd.start()

    # Create a test goal
    goal = gd.create_goal(
        title="Test goal",
        description="A test goal for self-testing",
        source="autonomous",
        priority=2,
        motivation="Testing the system",
        success_criteria="Test passes",
        steps=["Step 1", "Step 2", "Step 3"],
    )
    print(f"\nCreated goal: {goal.title} ({goal.goal_id})")

    # Update progress
    gd.update_progress(goal.goal_id, 0.5, milestone="Halfway there")
    print(f"Progress updated to 50%")

    # Get context
    ctx = gd.get_goal_context()
    print(f"\nGoal context:\n{ctx}")

    # Get stats
    stats = gd.get_stats()
    print(f"\nStats: {stats}")

    # Complete the goal
    gd.complete_goal(goal.goal_id, lesson="Test completed successfully")
    print(f"Goal completed!")

    gd.stop()
    print("\n✅ Goal Director self-test passed")
